In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits

In [3]:
dataset=load_digits()

In [4]:
dataset.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [5]:
dataset['data'].shape

(1797, 64)

In [6]:
dataset['target']

array([0, 1, 2, ..., 8, 9, 8])

In [7]:
dataset['target'].shape

(1797,)

In [8]:
X=dataset['data']

In [9]:
X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [11]:
y=dataset['target']

In [12]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [16]:
X_train.shape

(1347, 64)

In [17]:
def distance(a,b):
    return np.sum((b-a)**2)**0.5

In [18]:
def knn(X_train,y_train,test_point,k=5):
    distances=[]
    m=X_train.shape[0]
    for i in range(m):
        d=distance(test_point,X_train[i])
        distances.append([d,y_train[i]])
    sorted_dist=sorted(distances,key=lambda r:r[0])
    neighbors=np.asarray(sorted_dist)[:k,-1]
    freq=np.unique(neighbors,return_counts=True)
    index=freq[1].argmax()
    return freq[0][index]
        

In [19]:
knn(X_train,y_train,X_test[0])

9.0

In [21]:
y_test[0]

9

In [22]:
knn(X_train,y_train,X_test[1])

5.0

In [23]:
y_test[1]

5

In [24]:
def acc(k=5):
    predictions=[]
    m=X_test.shape[0]
    for i in range(m):
        test_point=X_test[i]
        pred_label=knn(X_train,y_train,test_point,k)
        predictions.append(pred_label)
    preds=np.asarray(predictions)
    return 100*(preds==y_test).sum()/m
    

In [26]:
acc()

99.11111111111111

In [27]:
acc(7)

99.11111111111111