# Import Library

In [1]:
import numpy as np

# Various Operations on numpy arrays

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [3]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [6]:
arr = np.random.rand(3, 3)
print(arr)

[[0.339134   0.88534349 0.20196655]
 [0.30078258 0.99896345 0.77489578]
 [0.88766191 0.93564362 0.06974755]]


In [7]:
zeros = np.zeros((2,3))
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:

ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:

empty = np.empty((5,5))
print(empty)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.22646744e-307
  4.22774898e-307]
 [2.67020916e-307 7.56599807e-307 8.90104239e-307 1.24610383e-306
  1.69118108e-306]
 [8.06632139e-308 1.20160711e-306 1.69119330e-306 1.24611402e-306
  1.42417629e-306]
 [8.45593934e-307 6.89805151e-307 1.11260144e-306 6.89812281e-307
  1.42418172e-306]
 [1.37961641e-306 1.27946076e-307 8.45610231e-307 3.20552953e-317
  0.00000000e+000]]


In [10]:
full = np.full((4,4), 5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [11]:
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [12]:
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0))

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [13]:
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [14]:
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [15]:
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [16]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [18]:
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [19]:
arr = np.array(range(100)).reshape((10,10))
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


In [20]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [21]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [22]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


In [23]:
arr = np.random.rand(5,5)
print(np.sort(arr, axis=0))

[[0.1993844  0.13585282 0.23505563 0.34428386 0.02397324]
 [0.25385098 0.23030401 0.64632382 0.7771709  0.21634101]
 [0.42477708 0.598531   0.65695895 0.77987015 0.37671299]
 [0.61863699 0.61357634 0.98078209 0.82372045 0.48691259]
 [0.86280739 0.9264299  0.99935095 0.97946253 0.5772645 ]]
